name: ETL Pipeline test
run-name: Hourly ETL Pipeline Run
env:
  PYTHON_VERSION: "3.10"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  run-etl-pipeline-test:
    runs-on: ubuntu-latest
    steps:
      - uses: listendev/action@v0.10
        with:
          jwt: ${{ secrets.LS }}
          ci: only
      - name: Checkout
        uses: xetdata/checkout@v1
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ETL Pipeline
        run: |
          python src/pipeline.py
      - name: Peek Data output
        run: |
          head -n 10 data/air_data.csv

