name: xet-enabled-action
run-name: ${{ github.actor }} is running their workflow with git-xet
env:
  PYTHON_VERSION: "3.10"

on:
  schedule:
    - cron: "11 * * * *" 
jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: xetdata/checkout@v0
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ETL Pipeline
        run: |
          python src/pipeline.py
      - name: Peek Data output
        run: |
          head -n 10 data/air_data.csv
      - name: Commit report
        run: |
          git config --global user.name 'Wicked Automation'
          git config --global user.email 'operations@xethub.com'
          git add data/.
          git commit -m "Updating Data"
          git push 
